symbol: RM
extends: _base
macro_lambda: 0.3
weights:
  supply: 0.3
  demand: 0.25
  inventory: 0.25
  spread: 0.1
  macro: 0.1
factors:
- code: RM_TS_ROLL_YIELD
  enabled: true
  weight_override: 0.15
- code: RM_STK_WARRANT
  enabled: true
  weight_override: 0.15
- code: RM_INV_PORT
  enabled: true
  weight_override: 0.12
